#include <algorithm>
#include <fs/network/poe_ninja/parse_data.hpp>
#include <fs/network/exceptions.hpp>
#include <fs/utility/dump_json.hpp>
#include <fs/utility/string_helpers.hpp>
#include <fs/lang/market/item_price_data.hpp>
#include <fs/lang/keywords.hpp>
#include <fs/log/logger.hpp>

#include <nlohmann/json.hpp>

#include <string_view>
#include <vector>

namespace fs::network::poe_ninja {

namespace {

template <typename F>
void for_each_item_impl(std::string_view json_str, const char* initial_key, log::logger& logger, F f)
{
	nlohmann::json json = nlohmann::json::parse(json_str);
	const auto it = json.find(initial_key);

	if (it == json.end()) {
		logger.error() << "Could not parse this JSON (first 200 characters): " << json_str.substr(0u, 200u);
		return;
	}

	for (const auto& item : *it) {
		try {
			f(item);
		}
		catch (const network::json_parse_error& e) {
			logger.warning() << "Failed to parse item entry: " << e.what()
				<< ", skipping this item: " << utility::dump_json(item) << '\n';
		}
		catch (const nlohmann::json::exception& e) {
			logger.warning() << e.what() << ", ignoring this item: " << utility::dump_json(item) << '\n';
		}
	}
}

}

namespace poe1 {

// autogenerated ninja's API doc: https://poe.ninja/swagger/index.html (no longer available)
namespace {

// taken from JavaScript code on the site
// static/js/economy/pages/CurrencyDetailsPage.tsx
lang::market::confidence_level currency_to_confidence_level(const nlohmann::json& item) // (only for currency overview items)
{
	/*
	 * This is a hard choice. poe.ninja reports separate confidence
	 * for buying and selling. Some items with very high demand have
	 * selling property equal to null, but this does not mean the item
	 * has low confidence - only that trades gets completed very fast
	 * which is the case for high-demand (often expensive) items.
	 *
	 * I have gone for some compromise. We treat an item as low-confidence
	 * when the sum of buying and selling offers is < 10.
	 */
	const auto get_count = [&](const auto& side_name) {
		const auto it = item.find(side_name);
		if (it == item.end() || it->is_null()) {
			return 0;
		}

		return it->at("count").template get<int>();
	};

	const auto total_count = get_count("pay") + get_count("receive");
	if (total_count < 10)
		return lang::market::confidence_level::low;
	else
		return lang::market::confidence_level::high;
}

lang::market::confidence_level to_confidence_level(int count)
{
	if (count < 5)
		return lang::market::confidence_level::low;
	else
		return lang::market::confidence_level::high;
}

template <typename F>
void for_each_item(std::string_view json_str, log::logger& logger, F f)
{
	for_each_item_impl(json_str, "lines", logger, f);
}

[[nodiscard]] const std::string&
get_item_property_name(const nlohmann::json& item)
{
	return item.at("name").get_ref<const std::string&>();
}

[[nodiscard]] bool
get_item_property_corrupted(const nlohmann::json& item)
{
	if (const auto it = item.find("corrupted"); it == item.end())
		return false;
	else
		return it->get<bool>();
}

[[nodiscard]] int
get_item_property_gem_quality(const nlohmann::json& item)
{
	if (const auto it = item.find("gemQuality"); it == item.end())
		return 0;
	else
		return it->get<int>();
}

[[nodiscard]] int
get_item_property_links(const nlohmann::json& item)
{
	if (const auto it = item.find("links"); it == item.end())
		return 0;
	else
		return it->get<int>();
}

[[nodiscard]] int
get_item_property_stack_size(const nlohmann::json& item)
{
	if (const auto it = item.find("stackSize"); it == item.end())
		return 1;
	else
		return it->get<int>();
}


[[nodiscard]] lang::influence_info
get_item_property_influence_info(const nlohmann::json& item)
{
	const auto it = item.find("variant");
	if (it == item.end())
		return {};

	if (it->is_null())
		return {};

	const auto& infl = it->get_ref<const nlohmann::json::string_t&>();

	// poe.ninja reports influence in strings as "X" or "X/Y"
	// so we can safely use string-contains approach
	return lang::influence_info{
		utility::contains(infl, "Shaper"),
		utility::contains(infl, "Elder"),
		utility::contains(infl, "Crusader"),
		utility::contains(infl, "Redeemer"),
		utility::contains(infl, "Hunter"),
		utility::contains(infl, "Warlord")
	};
}

[[nodiscard]] lang::market::price_data // (only for currency overview items)
get_currency_price_data(const nlohmann::json& item)
{
	return lang::market::price_data{
		item.at("chaosEquivalent").get<double>(),
		currency_to_confidence_level(item)
	};
}

[[nodiscard]] lang::market::price_data
get_item_price_data(const nlohmann::json& item)
{
	return lang::market::price_data{
		item.at("chaosValue").get<double>(),
		to_confidence_level(item.at("count").get<int>())
	};
}

[[nodiscard]] lang::market::elementary_item
get_currency_item_data(const nlohmann::json& item)
{
	return lang::market::elementary_item{
		get_currency_price_data(item),
		item.at("currencyTypeName").get<std::string>()
	};
}

[[nodiscard]] lang::market::elementary_item
get_elementary_item_data(const nlohmann::json& item)
{
	return lang::market::elementary_item{
		get_item_price_data(item),
		get_item_property_name(item),
	};
}

[[nodiscard]] std::vector<lang::market::elementary_item>
parse_currency_items(std::string_view json_str, log::logger& logger)
{
	std::vector<lang::market::elementary_item> result;

	for_each_item(json_str, logger, [&](const auto& item) {
		result.push_back(get_currency_item_data(item));
	});

	return result;
}

[[nodiscard]] std::vector<lang::market::elementary_item>
parse_elementary_items(std::string_view json_str, log::logger& logger)
{
	std::vector<lang::market::elementary_item> result;

	for_each_item(json_str, logger, [&](const auto& item) {
		result.push_back(get_elementary_item_data(item));
	});

	return result;
}

[[nodiscard]] std::vector<lang::market::poe1::divination_card>
parse_divination_cards(std::string_view json_str, log::logger& logger)
{
	std::vector<lang::market::poe1::divination_card> result;

	for_each_item(json_str, logger, [&](const nlohmann::json& item) {
		result.emplace_back(
			get_elementary_item_data(item),
			get_item_property_stack_size(item)
		);
	});

	return result;
}

[[nodiscard]] std::vector<lang::market::poe1::gem>
parse_gems(std::string_view json_str, log::logger& logger)
{
	std::vector<lang::market::poe1::gem> result;

	for_each_item(json_str, logger, [&](const nlohmann::json& item) {
		result.emplace_back(
			get_elementary_item_data(item),
			item.at("gemLevel").get<int>(),
			get_item_property_gem_quality(item),
			get_item_property_corrupted(item)
		);
	});

	return result;
}

[[nodiscard]] std::vector<lang::market::poe1::base>
parse_bases(std::string_view json_str, log::logger& logger)
{
	std::vector<lang::market::poe1::base> result;

	for_each_item(json_str, logger, [&](const nlohmann::json& item) {
		// yes, not really a proper name but poe.ninja reuses some fields for other purposes
		const auto item_level = item.at("levelRequired").get<int>();
		result.emplace_back(
			get_elementary_item_data(item),
			item_level,
			get_item_property_influence_info(item)
		);
	});

	return result;
}

void parse_and_fill_uniques(
	std::string_view uniques_json,
	lang::market::poe1::unique_item_price_data& uniques,
	log::logger& logger)
{
	for_each_item(uniques_json, logger, [&](const nlohmann::json& item) {
		// skip uniques which are linked
		if (get_item_property_links(item) == 6) {
			return;
		}

		// skip uniques which are relics
		// currently the only way to determine a unique item is relic is checking
		// the pattern inside "detailsId" field of the item
		if (const auto& details = item.at("detailsId").get_ref<const nlohmann::json::string_t&>();
			details.find("-relic") != std::string::npos)
		{
			return;
		}

		// skip uniques which do not drop (eg fated items) - this will reduce ambiguity and
		// not pollute the filter with items we would not care for
		const auto& name = get_item_property_name(item);
		if (lang::market::poe1::is_undroppable_unique(name)) {
			return;
		}

		const auto& base_type = item.at("baseType").get_ref<const nlohmann::json::string_t&>();
		uniques.add_item(base_type, lang::market::elementary_item{get_item_price_data(item), name});
	});
}

} // namespace

lang::market::poe1::item_price_data parse_item_price_data(const api_item_price_data& jsons, log::logger& logger)
{
	lang::market::poe1::item_price_data result;

	result.currency         = parse_currency_items(  jsons.currency.file_content,     logger);
	result.essences         = parse_elementary_items(jsons.essence.file_content,      logger);
	result.vials            = parse_elementary_items(jsons.vial.file_content,         logger);
	result.fossils          = parse_elementary_items(jsons.fossil.file_content,       logger);
	result.oils             = parse_elementary_items(jsons.oil.file_content,          logger);
	result.delirium_orbs    = parse_elementary_items(jsons.delirium_orb.file_content, logger);
	result.artifacts        = parse_elementary_items(jsons.artifact.file_content,     logger);
	result.tattoos          = parse_elementary_items(jsons.tattoo.file_content,       logger);
	result.omens            = parse_elementary_items(jsons.omen.file_content,         logger);
	result.runegrafts       = parse_elementary_items(jsons.runegraft.file_content,    logger);

	result.resonators       = parse_elementary_items(jsons.resonator.file_content, logger);

	result.divination_cards = parse_divination_cards(jsons.divination_card.file_content, logger);

	result.fragments        = parse_currency_items(  jsons.fragment.file_content, logger);
	result.scarabs          = parse_elementary_items(jsons.scarab.file_content, logger);
	result.allflame_embers  = parse_elementary_items(jsons.allflame_ember.file_content, logger);

	result.invitations      = parse_elementary_items(jsons.invitation.file_content, logger);

	result.incubators       = parse_elementary_items(jsons.incubator.file_content, logger);

	result.gems = parse_gems(jsons.skill_gem.file_content, logger);

	result.bases = parse_bases(jsons.base_type.file_content, logger);

	parse_and_fill_uniques(jsons.unique_armour.file_content,    result.unique_eq,        logger);
	parse_and_fill_uniques(jsons.unique_weapon.file_content,    result.unique_eq,        logger);
	parse_and_fill_uniques(jsons.unique_accessory.file_content, result.unique_eq,        logger);
	parse_and_fill_uniques(jsons.unique_flask.file_content,     result.unique_flasks,    logger);
	parse_and_fill_uniques(jsons.unique_tincture.file_content,  result.unique_tinctures, logger);
	parse_and_fill_uniques(jsons.unique_jewel.file_content,     result.unique_jewels,    logger);
	parse_and_fill_uniques(jsons.unique_map.file_content,       result.unique_maps,      logger);
	parse_and_fill_uniques(jsons.unique_relic.file_content,     result.unique_relics,    logger);
	parse_and_fill_uniques(jsons.unique_idol.file_content,      result.unique_idols,     logger);

	// TODO review items which might be miscategorized

	/*
	 * not all jsons are being read but:
	 * - we do not care about non-unique maps - people filter them by tier
	 * - we do not care about beasts - they do not drop
	 */
	return result;
}

} // namespace poe1

namespace poe2 {

namespace {

[[nodiscard]] lang::market::elementary_item
get_elementary_item_data(const nlohmann::json& item)
{
	return lang::market::elementary_item{
		lang::market::price_data{
			item.at("primaryValue").get<double>(),
			// data in PoE 2 is always high confidence (straight from currency exchange)
			lang::market::confidence_level::high
		},
		item.at("item").at("name").get_ref<const std::string&>()
	};
}

template <typename F>
void for_each_item(std::string_view json_str, log::logger& logger, F f)
{
	for_each_item_impl(json_str, "items", logger, f);
}

[[nodiscard]] std::vector<lang::market::elementary_item>
parse_elementary_items(std::string_view json_str, log::logger& logger)
{
	std::vector<lang::market::elementary_item> result;

	for_each_item(json_str, logger, [&](const auto& item) {
		result.push_back(get_elementary_item_data(item));
	});

	return result;
}

void parse_uncut_gems(
	std::string_view json_str,
	std::vector<lang::market::elementary_item>& uncut_skill_gems,
	std::vector<lang::market::elementary_item>& uncut_spirit_gems,
	log::logger& logger)
{
	std::vector<lang::market::elementary_item> uncut_gems = parse_elementary_items(json_str, logger);

	for (auto& uncut_gem: uncut_gems) {
		if (utility::contains(uncut_gem.name, "Skill"))
			uncut_skill_gems.push_back(std::move(uncut_gem));
		else if (utility::contains(uncut_gem.name, "Spirit"))
			uncut_spirit_gems.push_back(std::move(uncut_gem));
	}
}

// poe.ninja sorts items by mechanical themes instead of filter item classes.
// For example, many Splinters are grouped with other items from same mechanic or
// put into Fragments even though they are technically "Stackable Currency".
// This function exists to adjust categorization for filter purposes.
void move_item(
	std::string_view name,
	std::vector<lang::market::elementary_item>& from,
	std::vector<lang::market::elementary_item>& to)
{
	const auto it = std::find_if(
		from.begin(),
		from.end(),
		[&](const lang::market::elementary_item& item) { return item.name == name; });

	if (it == from.end())
		return;

	to.push_back(std::move(*it));
	from.erase(it);
}

} // namespace

lang::market::poe2::item_price_data parse_item_price_data(const api_item_price_data& jsons, log::logger& logger)
{
	lang::market::poe2::item_price_data result;

	result.currency             = parse_elementary_items(jsons.currency.file_content, logger);
	result.fragments            = parse_elementary_items(jsons.fragments.file_content, logger);
	result.abyss_currency       = parse_elementary_items(jsons.abyss.file_content, logger);
	parse_uncut_gems(jsons.uncut_gems.file_content, result.uncut_skill_gems, result.uncut_spirit_gems, logger);
	result.lineage_support_gems = parse_elementary_items(jsons.lineage_support_gems.file_content, logger);
	result.essences             = parse_elementary_items(jsons.essences.file_content, logger);
	result.soul_cores           = parse_elementary_items(jsons.ultimatum.file_content, logger);
	result.talismans            = parse_elementary_items(jsons.talismans.file_content, logger);
	result.runes                = parse_elementary_items(jsons.runes.file_content, logger);
	result.omens                = parse_elementary_items(jsons.ritual.file_content, logger);
	result.expedition           = parse_elementary_items(jsons.expedition.file_content, logger);
	result.emotions             = parse_elementary_items(jsons.delirium.file_content, logger);
	result.catalysts            = parse_elementary_items(jsons.breach.file_content, logger);

	// poe.ninja reports chaos value so it doesn't report Chaos Orb.
	result.currency.push_back(lang::market::elementary_item{
		lang::market::price_data{1.0, lang::market::confidence_level::high}, "Chaos Orb"});

	move_item("Kulemak's Invitation", result.abyss_currency, result.fragments);

	move_item("Runic Splinter", result.fragments,  result.currency);
	move_item("Runic Splinter", result.expedition, result.currency);

	move_item("Petition Splinter", result.fragments, result.currency);
	move_item("Petition Splinter", result.omens,     result.currency);

	move_item("Simulacrum Splinter", result.fragments, result.currency);
	move_item("Simulacrum Splinter", result.emotions,  result.currency);

	move_item("Breach Splinter", result.fragments, result.currency);
	move_item("Breach Splinter", result.catalysts, result.currency);

	return result;
}

} // namespace poe2

}
