#include <fs/network/poe_ninja/parse_data.hpp>
#include <fs/network/exceptions.hpp>
#include <fs/utility/assert.hpp>
#include <fs/utility/math.hpp>
#include <fs/utility/dump_json.hpp>
#include <fs/utility/string_helpers.hpp>
#include <fs/lang/market/item_price_data.hpp>
#include <fs/lang/keywords.hpp>
#include <fs/log/logger.hpp>

#include <nlohmann/json.hpp>

#include <algorithm>
#include <string_view>
#include <vector>

namespace fs::network::poe_ninja {

using fs::utility::is_zero;

namespace {

void print_file_parse_error(std::string_view json_str, log::logger& logger)
{
	logger.error() << "Could not parse this JSON (first 200 characters): " << json_str.substr(0u, 200u);
}

template <typename F>
void for_each_item_in_items(const nlohmann::json& items, log::logger& logger, F f)
{
	for (const auto& item : items) {
		try {
			f(item);
		}
		catch (const network::json_parse_error& e) {
			logger.warning() << "Failed to parse item entry: " << e.what()
				<< ", skipping this item: " << utility::dump_json(item) << '\n';
		}
		catch (const nlohmann::json::exception& e) {
			logger.warning() << e.what() << ", ignoring this item: " << utility::dump_json(item) << '\n';
		}
	}
}

// Sometimes main currencies (Chaos, Exalted, Divine) are not reported. Add them if missing, based on known rates
void add_missing_currencies(std::vector<lang::market::elementary_item>& currency, lang::market::currency_exchange_rates rates)
{
	auto has_item = [&](const char* item_name) {
		return std::any_of(
			currency.begin(),
			currency.end(),
			[&](const lang::market::elementary_item& item) { return item.name == item_name; });
	};

	if (!has_item("Chaos Orb")) {
		lang::market::price_data price_data;
		price_data.confidence = lang::market::confidence_level::high;
		price_data.value_chaos = 1.0;
		price_data.value_exalted = 1.0 / rates.exalted_to_chaos;
		price_data.value_divine = 1.0 / rates.divine_to_chaos;
		currency.push_back(lang::market::elementary_item{price_data, "Chaos Orb"});
	}

	if (!has_item("Exalted Orb")) {
		lang::market::price_data price_data;
		price_data.confidence = lang::market::confidence_level::high;
		price_data.value_chaos = rates.exalted_to_chaos;
		price_data.value_exalted = 1.0;
		price_data.value_divine = 1.0 / rates.divine_to_exalted;
		currency.push_back(lang::market::elementary_item{price_data, "Exalted Orb"});
	}

	if (!has_item("Divine Orb")) {
		lang::market::price_data price_data;
		price_data.confidence = lang::market::confidence_level::high;
		price_data.value_chaos = rates.divine_to_chaos;
		price_data.value_exalted = rates.divine_to_exalted;
		price_data.value_divine = 1.0;
		currency.push_back(lang::market::elementary_item{price_data, "Divine Orb"});
	}
}

// poe.ninja sorts items by mechanical themes instead of filter item classes.
// For example, many Splinters are grouped with other items from same mechanic or
// put into Fragments even though they are technically "Stackable Currency".
// This function exists to adjust categorization for filter purposes.
void move_item(
	std::string_view name,
	std::vector<lang::market::elementary_item>& from,
	std::vector<lang::market::elementary_item>& to)
{
	const auto it = std::find_if(
		from.begin(),
		from.end(),
		[&](const lang::market::elementary_item& item) { return item.name == name; });

	if (it == from.end())
		return;

	to.push_back(std::move(*it));
	from.erase(it);
}

}

namespace poe1 {

// autogenerated ninja's API doc: https://poe.ninja/swagger/index.html (no longer available)
namespace {

// taken from JavaScript code on the site
// static/js/economy/pages/CurrencyDetailsPage.tsx
lang::market::confidence_level currency_to_confidence_level(const nlohmann::json& item) // (only for currency overview items)
{
	/*
	 * This is a hard choice. poe.ninja reports separate confidence
	 * for buying and selling. Some items with very high demand have
	 * selling property equal to null, but this does not mean the item
	 * has low confidence - only that trades gets completed very fast
	 * which is the case for high-demand (often expensive) items.
	 *
	 * I have gone for some compromise. We treat an item as low-confidence
	 * when the sum of buying and selling offers is < 10.
	 */
	const auto get_count = [&](const auto& side_name) {
		const auto it = item.find(side_name);
		if (it == item.end() || it->is_null()) {
			return 0;
		}

		return it->at("count").template get<int>();
	};

	const auto total_count = get_count("pay") + get_count("receive");
	if (total_count < 10)
		return lang::market::confidence_level::low;
	else
		return lang::market::confidence_level::high;
}

lang::market::confidence_level to_confidence_level(int count)
{
	if (count < 5)
		return lang::market::confidence_level::low;
	else
		return lang::market::confidence_level::high;
}

template <typename F>
void for_each_item_in_json(std::string_view json_str, log::logger& logger, F f)
{
	const nlohmann::json json = nlohmann::json::parse(json_str);
	const auto it = json.find("lines");

	if (it == json.end()) {
		print_file_parse_error(json_str, logger);
		return;
	}

	for_each_item_in_items(*it, logger, f);
}

[[nodiscard]] const std::string&
get_item_property_name(const nlohmann::json& item)
{
	return item.at("name").get_ref<const std::string&>();
}

[[nodiscard]] bool
get_item_property_corrupted(const nlohmann::json& item)
{
	if (const auto it = item.find("corrupted"); it == item.end())
		return false;
	else
		return it->get<bool>();
}

[[nodiscard]] int
get_item_property_gem_quality(const nlohmann::json& item)
{
	if (const auto it = item.find("gemQuality"); it == item.end())
		return 0;
	else
		return it->get<int>();
}

[[nodiscard]] int
get_item_property_links(const nlohmann::json& item)
{
	if (const auto it = item.find("links"); it == item.end())
		return 0;
	else
		return it->get<int>();
}

[[nodiscard]] int
get_item_property_stack_size(const nlohmann::json& item)
{
	if (const auto it = item.find("stackSize"); it == item.end())
		return 1;
	else
		return it->get<int>();
}


[[nodiscard]] lang::influence_info
get_item_property_influence_info(const nlohmann::json& item)
{
	const auto it = item.find("variant");
	if (it == item.end())
		return {};

	if (it->is_null())
		return {};

	const auto& infl = it->get_ref<const nlohmann::json::string_t&>();

	// poe.ninja reports influence in strings as "X" or "X/Y"
	// so we can safely use string-contains approach
	return lang::influence_info{
		utility::contains(infl, "Shaper"),
		utility::contains(infl, "Elder"),
		utility::contains(infl, "Crusader"),
		utility::contains(infl, "Redeemer"),
		utility::contains(infl, "Hunter"),
		utility::contains(infl, "Warlord")
	};
}

[[nodiscard]] lang::market::price_data // (only for currency overview items)
get_currency_price_data(const nlohmann::json& item)
{
	lang::market::price_data price_data;
	price_data.confidence = currency_to_confidence_level(item);
	price_data.value_chaos = item.at("chaosEquivalent").get<double>();
	return price_data;
}

[[nodiscard]] lang::market::price_data
get_item_price_data(const nlohmann::json& item)
{
	lang::market::price_data price_data;
	price_data.confidence = to_confidence_level(item.at("count").get<int>());
	price_data.value_chaos = item.at("chaosValue").get<double>();
	return price_data;
}

[[nodiscard]] lang::market::elementary_item
get_currency_item_data(const nlohmann::json& item)
{
	return lang::market::elementary_item{
		get_currency_price_data(item),
		item.at("currencyTypeName").get<std::string>()
	};
}

[[nodiscard]] lang::market::elementary_item
get_elementary_item_data(const nlohmann::json& item)
{
	return lang::market::elementary_item{
		get_item_price_data(item),
		get_item_property_name(item),
	};
}

[[nodiscard]] std::vector<lang::market::elementary_item>
parse_currency_items(std::string_view json_str, log::logger& logger)
{
	std::vector<lang::market::elementary_item> result;

	for_each_item_in_json(json_str, logger, [&](const auto& item) {
		result.push_back(get_currency_item_data(item));
	});

	return result;
}

[[nodiscard]] std::vector<lang::market::elementary_item>
parse_elementary_items(std::string_view json_str, log::logger& logger)
{
	std::vector<lang::market::elementary_item> result;

	for_each_item_in_json(json_str, logger, [&](const auto& item) {
		result.push_back(get_elementary_item_data(item));
	});

	return result;
}

[[nodiscard]] std::vector<lang::market::poe1::divination_card>
parse_divination_cards(std::string_view json_str, log::logger& logger)
{
	std::vector<lang::market::poe1::divination_card> result;

	for_each_item_in_json(json_str, logger, [&](const nlohmann::json& item) {
		result.emplace_back(
			get_elementary_item_data(item),
			get_item_property_stack_size(item)
		);
	});

	return result;
}

[[nodiscard]] std::vector<lang::market::poe1::gem>
parse_gems(std::string_view json_str, log::logger& logger)
{
	std::vector<lang::market::poe1::gem> result;

	for_each_item_in_json(json_str, logger, [&](const nlohmann::json& item) {
		result.emplace_back(
			get_elementary_item_data(item),
			item.at("gemLevel").get<int>(),
			get_item_property_gem_quality(item),
			get_item_property_corrupted(item)
		);
	});

	return result;
}

[[nodiscard]] std::vector<lang::market::poe1::base>
parse_bases(std::string_view json_str, log::logger& logger)
{
	std::vector<lang::market::poe1::base> result;

	for_each_item_in_json(json_str, logger, [&](const nlohmann::json& item) {
		// yes, not really a proper name but poe.ninja reuses some fields for other purposes
		const auto item_level = item.at("levelRequired").get<int>();
		result.emplace_back(
			get_elementary_item_data(item),
			item_level,
			get_item_property_influence_info(item)
		);
	});

	return result;
}

void parse_and_fill_uniques(
	std::string_view uniques_json,
	lang::market::poe1::unique_item_price_data& uniques,
	log::logger& logger)
{
	for_each_item_in_json(uniques_json, logger, [&](const nlohmann::json& item) {
		// skip uniques which are linked
		if (get_item_property_links(item) == 6) {
			return;
		}

		// skip uniques which are relics
		// currently the only way to determine a unique item is relic is checking
		// the pattern inside "detailsId" field of the item
		if (const auto& details = item.at("detailsId").get_ref<const nlohmann::json::string_t&>();
			details.find("-relic") != std::string::npos)
		{
			return;
		}

		// skip uniques which do not drop (eg fated items) - this will reduce ambiguity and
		// not pollute the filter with items we would not care for
		const auto& name = get_item_property_name(item);
		if (lang::market::poe1::is_undroppable_unique(name)) {
			return;
		}

		const auto& base_type = item.at("baseType").get_ref<const nlohmann::json::string_t&>();
		uniques.add_item(base_type, lang::market::elementary_item{get_item_price_data(item), name});
	});
}

lang::market::currency_exchange_rates infer_exchange_rates(const std::vector<lang::market::elementary_item>& currency, log::logger& logger)
{
	const auto find_item = [&](const char* item_name) {
		return std::find_if(currency.begin(), currency.end(), [&](const lang::market::elementary_item& item) { return item.name == item_name; });
	};

	lang::market::currency_exchange_rates rates;

	const auto it_exalted = find_item("Exalted Orb");
	if (it_exalted == currency.end()) {
		logger.warning() << "Could not find \"Exalted Orb\" in currency data. Items will not have Exalted value availalbe.";
	}
	else {
		rates.exalted_to_chaos = it_exalted->price.value_chaos;
	}

	const auto it_divine = find_item("Divine Orb");
	if (it_divine == currency.end()) {
		logger.warning() << "Could not find \"Divine Orb\" in currency data. Items will not have Divine value availalbe.";
	}
	else {
		rates.divine_to_chaos = it_divine->price.value_chaos;
	}

	if (!is_zero(rates.exalted_to_chaos) && !is_zero(rates.divine_to_chaos))
		rates.divine_to_exalted = rates.divine_to_chaos / rates.exalted_to_chaos;

	return rates;
}

void update_non_chaos_prices(lang::market::elementary_item& item, lang::market::currency_exchange_rates rates)
{
	if (!is_zero(rates.divine_to_chaos))
		item.price.value_divine = item.price.value_chaos / rates.divine_to_chaos;

	if (!is_zero(rates.divine_to_chaos))
		item.price.value_exalted = item.price.value_chaos / rates.exalted_to_chaos;
}

template <typename Item>
void update_non_chaos_prices(std::vector<Item>& items, lang::market::currency_exchange_rates rates)
{
	static_assert(std::is_base_of_v<lang::market::elementary_item, Item>);

	for (Item& item : items)
		update_non_chaos_prices(item, rates);
}

void update_non_chaos_prices(lang::market::poe1::unique_item_price_data& items, lang::market::currency_exchange_rates rates)
{
	for (auto& item : items.unambiguous)
		update_non_chaos_prices(item.second, rates);

	for (auto& items : items.ambiguous)
		update_non_chaos_prices(items.second, rates);
}

} // namespace

lang::market::poe1::item_price_data parse_item_price_data(const api_item_price_data& jsons, log::logger& logger)
{
	/**
	 * PoE 1 data reports prices only as Chaos.
	 * First parse everything, filling only value_chaos field,
	 * then update all items based on exchange rates.
	 */
	lang::market::poe1::item_price_data result;

	result.currency         = parse_currency_items(  jsons.currency.file_content,     logger);
	result.essences         = parse_elementary_items(jsons.essence.file_content,      logger);
	result.vials            = parse_elementary_items(jsons.vial.file_content,         logger);
	result.fossils          = parse_elementary_items(jsons.fossil.file_content,       logger);
	result.oils             = parse_elementary_items(jsons.oil.file_content,          logger);
	result.delirium_orbs    = parse_elementary_items(jsons.delirium_orb.file_content, logger);
	result.artifacts        = parse_elementary_items(jsons.artifact.file_content,     logger);
	result.tattoos          = parse_elementary_items(jsons.tattoo.file_content,       logger);
	result.omens            = parse_elementary_items(jsons.omen.file_content,         logger);
	result.runegrafts       = parse_elementary_items(jsons.runegraft.file_content,    logger);

	result.resonators       = parse_elementary_items(jsons.resonator.file_content, logger);

	result.divination_cards = parse_divination_cards(jsons.divination_card.file_content, logger);

	result.fragments        = parse_currency_items(  jsons.fragment.file_content, logger);
	result.scarabs          = parse_elementary_items(jsons.scarab.file_content, logger);
	result.allflame_embers  = parse_elementary_items(jsons.allflame_ember.file_content, logger);

	result.invitations      = parse_elementary_items(jsons.invitation.file_content, logger);

	result.incubators       = parse_elementary_items(jsons.incubator.file_content, logger);

	result.gems = parse_gems(jsons.skill_gem.file_content, logger);

	result.bases = parse_bases(jsons.base_type.file_content, logger);

	parse_and_fill_uniques(jsons.unique_armour.file_content,    result.unique_eq,        logger);
	parse_and_fill_uniques(jsons.unique_weapon.file_content,    result.unique_eq,        logger);
	parse_and_fill_uniques(jsons.unique_accessory.file_content, result.unique_eq,        logger);
	parse_and_fill_uniques(jsons.unique_flask.file_content,     result.unique_flasks,    logger);
	parse_and_fill_uniques(jsons.unique_tincture.file_content,  result.unique_tinctures, logger);
	parse_and_fill_uniques(jsons.unique_jewel.file_content,     result.unique_jewels,    logger);
	parse_and_fill_uniques(jsons.unique_map.file_content,       result.unique_maps,      logger);
	parse_and_fill_uniques(jsons.unique_relic.file_content,     result.unique_relics,    logger);
	parse_and_fill_uniques(jsons.unique_idol.file_content,      result.unique_idols,     logger);

	// TODO "Misc Map Items"? Can all fragments be caught as "Map Fragments"?
	move_item("Valdo's Puzzle Box",               result.fragments, result.currency);
	move_item("Crescent Splinter",                result.fragments, result.currency);
	move_item("Simulacrum Splinter",              result.fragments, result.currency);
	move_item("Splinter of Xoph",                 result.fragments, result.currency);
	move_item("Splinter of Tul",                  result.fragments, result.currency);
	move_item("Splinter of Esh",                  result.fragments, result.currency);
	move_item("Splinter of Uul-Netol",            result.fragments, result.currency);
	move_item("Splinter of Chayula",              result.fragments, result.currency);
	move_item("Timeless Vaal Splinter",           result.fragments, result.currency);
	move_item("Timeless Karui Splinter",          result.fragments, result.currency);
	move_item("Timeless Eternal Empire Splinter", result.fragments, result.currency);
	move_item("Timeless Templar Splinter",        result.fragments, result.currency);
	move_item("Timeless Maraketh Splinter",       result.fragments, result.currency);

	result.rates = infer_exchange_rates(result.currency, logger);
	add_missing_currencies(result.currency, result.rates);

	update_non_chaos_prices(result.currency,         result.rates);
	update_non_chaos_prices(result.essences,         result.rates);
	update_non_chaos_prices(result.vials,            result.rates);
	update_non_chaos_prices(result.fossils,          result.rates);
	update_non_chaos_prices(result.oils,             result.rates);
	update_non_chaos_prices(result.delirium_orbs,    result.rates);
	update_non_chaos_prices(result.artifacts,        result.rates);
	update_non_chaos_prices(result.tattoos,          result.rates);
	update_non_chaos_prices(result.omens,            result.rates);
	update_non_chaos_prices(result.runegrafts,       result.rates);
	update_non_chaos_prices(result.resonators,       result.rates);
	update_non_chaos_prices(result.divination_cards, result.rates);
	update_non_chaos_prices(result.fragments,        result.rates);
	update_non_chaos_prices(result.scarabs,          result.rates);
	update_non_chaos_prices(result.allflame_embers,  result.rates);
	update_non_chaos_prices(result.invitations,      result.rates);
	update_non_chaos_prices(result.incubators,       result.rates);
	update_non_chaos_prices(result.gems,             result.rates);
	update_non_chaos_prices(result.bases,            result.rates);
	update_non_chaos_prices(result.unique_eq,        result.rates);
	update_non_chaos_prices(result.unique_flasks,    result.rates);
	update_non_chaos_prices(result.unique_tinctures, result.rates);
	update_non_chaos_prices(result.unique_jewels,    result.rates);
	update_non_chaos_prices(result.unique_maps,      result.rates);
	update_non_chaos_prices(result.unique_relics,    result.rates);
	update_non_chaos_prices(result.unique_idols,     result.rates);

	/*
	 * not all jsons are being read but:
	 * - we do not care about non-unique maps - people filter them by tier
	 * - we do not care about beasts - they do not drop
	 */
	return result;
}

} // namespace poe1

namespace poe2 {

namespace {

enum class primary_currency { chaos, exalted, divine };
struct primary_currency_info
{
	primary_currency primary;
	lang::market::currency_exchange_rates rates;
};

std::optional<primary_currency_info> infer_primary_currency_info(const nlohmann::json& json, log::logger& logger)
{
	const auto it_core = json.find("core");
	if (it_core == json.end()) {
		logger.error() << "Could not find \"core\" subobject in JSON";
		return std::nullopt;
	}

	const auto it_primary = it_core->find("primary");
	if (it_primary == it_core->end()) {
		logger.error() << "Could not find \"core\".\"primary\" subobject in JSON";
		return std::nullopt;
	}

	primary_currency_info info;
	const auto& primary_currency = it_primary->get_ref<const std::string&>();

	if (primary_currency == "chaos")
		info.primary = primary_currency::chaos;
	else if (primary_currency == "exalted")
		info.primary = primary_currency::exalted;
	else if (primary_currency == "divine")
		info.primary = primary_currency::divine;
	else {
		logger.error() << "Unknown primary currency: \"" << primary_currency << "\"";
		return std::nullopt;
	}

	const auto it_rates = it_core->find("rates");
	if (it_rates == it_core->end()) {
		logger.error() << "Could not find \"core\".\"rates\" subobject in JSON";
		return std::nullopt;
	}

	const auto get_rate = [&](const char* name) -> std::optional<double> {
		const auto it = it_rates->find(name);
		if (it == it_rates->end()) {
			logger.error() << "Could not find \"core\".\"rates\".\"" << name << "\" subobject in JSON";
			return std::nullopt;
		};
		return it->get<double>();
	};

	if (info.primary == primary_currency::chaos) {
		auto chaos_to_exalted = get_rate("exalted");
		if (chaos_to_exalted == std::nullopt)
			return std::nullopt;
		info.rates.exalted_to_chaos = 1.0 / *chaos_to_exalted;

		auto chaos_to_divine = get_rate("divine");
		if (chaos_to_divine == std::nullopt)
			return std::nullopt;
		info.rates.divine_to_chaos = 1.0 / *chaos_to_divine;

		info.rates.divine_to_exalted = info.rates.divine_to_chaos / info.rates.exalted_to_chaos;
	}
	else if (info.primary == primary_currency::exalted) {
		auto exalted_to_chaos = get_rate("chaos");
		if (exalted_to_chaos == std::nullopt)
			return std::nullopt;
		info.rates.exalted_to_chaos = *exalted_to_chaos;

		auto exalted_to_divine = get_rate("divine");
		if (exalted_to_divine == std::nullopt)
			return std::nullopt;
		info.rates.divine_to_exalted = 1.0 / *exalted_to_divine;

		info.rates.divine_to_chaos = info.rates.divine_to_exalted * info.rates.exalted_to_chaos;
	}
	else {
		FS_ASSERT(info.primary == primary_currency::divine);

		auto divine_to_chaos = get_rate("chaos");
		if (divine_to_chaos == std::nullopt)
			return std::nullopt;
		info.rates.divine_to_chaos = *divine_to_chaos;

		auto divine_to_exalted = get_rate("exalted");
		if (divine_to_exalted == std::nullopt)
			return std::nullopt;
		info.rates.divine_to_exalted = *divine_to_exalted;

		info.rates.exalted_to_chaos = info.rates.divine_to_chaos / info.rates.divine_to_exalted;
	}

	return info;
}

lang::market::price_data compute_item_price(double primary_value, primary_currency_info info)
{
	lang::market::price_data price_data;
	// data from currency exchange API is always high confidence
	// (and this function is only used for such items)
	price_data.confidence = lang::market::confidence_level::high;

	if (info.primary == primary_currency::chaos) {
		price_data.value_chaos = primary_value;
		price_data.value_exalted = price_data.value_chaos / info.rates.exalted_to_chaos;
		price_data.value_divine  = price_data.value_chaos / info.rates.divine_to_chaos;
	}
	else if (info.primary == primary_currency::exalted) {
		price_data.value_exalted = primary_value;
		price_data.value_chaos  = price_data.value_exalted * info.rates.exalted_to_chaos;
		price_data.value_divine = price_data.value_exalted / info.rates.divine_to_exalted;
	}
	else {
		FS_ASSERT(info.primary == primary_currency::divine);
		price_data.value_divine = primary_value;
		price_data.value_chaos   = price_data.value_divine * info.rates.divine_to_chaos;
		price_data.value_exalted = price_data.value_divine * info.rates.divine_to_exalted;
	}

	return price_data;
}

[[nodiscard]] std::vector<lang::market::elementary_item>
parse_elementary_items(std::string_view json_str, log::logger& logger)
{
	std::vector<lang::market::elementary_item> result;

	std::unordered_map<std::string, std::string> item_ids_to_names;

	const nlohmann::json json = nlohmann::json::parse(json_str);

	std::optional<primary_currency_info> info = infer_primary_currency_info(json, logger);
	if (info == std::nullopt)
		return {};

	const auto it_items = json.find("items"); // item id => item description (includes name)
	const auto it_lines = json.find("lines"); // item id => item value

	if (it_lines == json.end() || it_items == json.end()) {
		print_file_parse_error(json_str, logger);
		return {};
	}

	item_ids_to_names.reserve(it_items->size());

	for_each_item_in_items(*it_items, logger, [&](const nlohmann::json& item) {
		item_ids_to_names.emplace(item.at("id"), item.at("name"));
	});

	for_each_item_in_items(*it_lines, logger, [&](const nlohmann::json& item) {
		const auto id = item.at("id").get_ref<const std::string&>();
		const auto name_it = item_ids_to_names.find(id);

		if (name_it == item_ids_to_names.end()) {
			logger.error() << "Price data for item with id = \"" << id << "\" has no item associated";
			return;
		}

		result.push_back(lang::market::elementary_item{
			compute_item_price(item.at("primaryValue").get<double>(), *info),
			name_it->second
		});
	});

	return result;
}

void parse_uncut_gems(
	std::string_view json_str,
	std::vector<lang::market::elementary_item>& uncut_skill_gems,
	std::vector<lang::market::elementary_item>& uncut_spirit_gems,
	log::logger& logger)
{
	std::vector<lang::market::elementary_item> uncut_gems = parse_elementary_items(json_str, logger);

	for (auto& uncut_gem: uncut_gems) {
		if (utility::contains(uncut_gem.name, "Skill"))
			uncut_skill_gems.push_back(std::move(uncut_gem));
		else if (utility::contains(uncut_gem.name, "Spirit"))
			uncut_spirit_gems.push_back(std::move(uncut_gem));
	}
}

} // namespace

lang::market::poe2::item_price_data parse_item_price_data(const api_item_price_data& jsons, log::logger& logger)
{
	/**
	 * PoE 2 data reports prices only as a single currency, named "primary".
	 * Each JSON may have different primary currency (Chaos, Exalted or Divine).
	 * When parsing each JSON, first read core information to infer exchange rates
	 * (this is done inside poe2::parse_elementary_items).
	 */
	lang::market::poe2::item_price_data result;

	const std::optional<primary_currency_info> info = infer_primary_currency_info(nlohmann::json::parse(jsons.currency.file_content), logger);
	if (info == std::nullopt) {
		logger.error() << "Could not parse primary currency info";
		return {};
	}
	result.rates = (*info).rates;

	result.currency             = parse_elementary_items(jsons.currency.file_content, logger);
	result.fragments            = parse_elementary_items(jsons.fragments.file_content, logger);
	result.abyss_currency       = parse_elementary_items(jsons.abyss.file_content, logger);
	parse_uncut_gems(jsons.uncut_gems.file_content, result.uncut_skill_gems, result.uncut_spirit_gems, logger);
	result.lineage_support_gems = parse_elementary_items(jsons.lineage_support_gems.file_content, logger);
	result.essences             = parse_elementary_items(jsons.essences.file_content, logger);
	result.soul_cores           = parse_elementary_items(jsons.ultimatum.file_content, logger);
	result.idols                = parse_elementary_items(jsons.idols.file_content, logger);
	result.runes                = parse_elementary_items(jsons.runes.file_content, logger);
	result.omens                = parse_elementary_items(jsons.ritual.file_content, logger);
	result.expedition           = parse_elementary_items(jsons.expedition.file_content, logger);
	result.emotions             = parse_elementary_items(jsons.delirium.file_content, logger);
	result.catalysts            = parse_elementary_items(jsons.breach.file_content, logger);

	add_missing_currencies(result.currency, result.rates);

	move_item("Kulemak's Invitation", result.abyss_currency, result.fragments);

	move_item("Runic Splinter", result.fragments,  result.currency);
	move_item("Runic Splinter", result.expedition, result.currency);

	move_item("Petition Splinter", result.fragments, result.currency);
	move_item("Petition Splinter", result.omens,     result.currency);

	move_item("Simulacrum Splinter", result.fragments, result.currency);
	move_item("Simulacrum Splinter", result.emotions,  result.currency);

	move_item("Breach Splinter", result.fragments, result.currency);
	move_item("Breach Splinter", result.catalysts, result.currency);

	for (auto name : {"Amanamu's Gaze", "Tecrod's Gaze", "Kurgal's Gaze", "Ulaman's Gaze"})
		move_item(name, result.abyss_currency, result.runes);

	return result;
}

} // namespace poe2

}
